---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: frost987/web-app:latest
        ports:
        - containerPort: 4567
---

apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: web-app
  name: webapp-services
  namespace: default
spec:
  ports:
    - port: 4567
      targetPort: 4567
  selector:
    k8s-app: web-app
  type: NodePort

---

apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    k8s-app: web-app

spec:
  containers:
    - name: web-app
      image: frost987/web-app
---
