---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: frost987/web-app:latest
        ports:
        - containerPort: 4567
---

apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: webapp
  name: webapp-services
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 4567
  selector:
    k8s-app: webapp
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  clusterIP: None
  ports:
    -
      name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
  externalIPs:
    - 192.168.0.64

---

kind: Endpoints
apiVersion: v1
metadata:
  name: mysql
subsets:
  -
    addresses:
      -
        ip: 192.168.0.47
    ports:
      -
        port: 3306
        name: mysql
---

apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    k8s-app: webapp

spec:
  containers:
    - name: webapp
      image: frost987/web-app
---
